version: "3.5"

services:
  jekyll:
    environment:
      - JEKYLL_ENV=production
    build:
      context: ./
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    command: bundle exec jekyll serve --host 0.0.0.0 --config _config.yml,_config_docker.yml

